Fix `setup_scala_testing_toolchain()` classpaths (#1707)
* Fix `setup_scala_testing_toolchain()` classpaths

Fixes #1706. Removes the addition of the Scala version suffix to
`*_classpath` argument labels in `setup_scala_testing_toolchain()`.

To facilitate the fix:

- Moves everything from `testing/deps.bzl` into `testing/testing.bzl`
  and removes the original `testing/deps.bzl` file.

- Updates `repositories()` from `scala/scala_cross_version.bzl` to
  accept and return `None` as an argument.

- Updates `examples/testing/multi_frameworks_toolchain/BUILD` to provide
  a reproduction and validation of the fix.

After updating `multi_frameworks_toolchain/BUILD`, but before applying
the fix, the `multi_framework_toolchain_example` test case broke in a
similar fashion to #1706:

```txt
$ RULES_SCALA_TEST_ONLY=multi_framework_toolchain_example \
  ./test_examples.sh

running test multi_framework_toolchain_example
ERROR: .../examples/testing/multi_frameworks_toolchain/BUILD:19:30:
  no such package '@io_bazel_rules_scala_org_specs2_specs2_fp_2_12_20_2_12_20//':
  The repository '@io_bazel_rules_scala_org_specs2_specs2_fp_2_12_20_2_12_20'
  could not be resolved:
  Repository '@io_bazel_rules_scala_org_specs2_specs2_fp_2_12_20_2_12_20'
  is not defined and referenced by '//:testing_toolchain_specs2_classpath_provider'

ERROR: Analysis of target
  '//:testing_toolchain_specs2_classpath_provider' failed;
  build aborted:
Analysis failed
INFO: Elapsed time: 0.159s
INFO: 0 processes.
ERROR: Couldn't start the build. Unable to run tests
```

* Fix `repositories()` docstring grammatical error