Fix `test_bzlmod_macros` on Windows, Java 21 build
Copies `tools/bazel.rc` to the test repos generated by
`test_bzlmod_macros` to fix the `test_rules_scala_jdk21` CI job.
Updates `_print_error_msg()` to fix Windows error output, and uses
relative paths with `local_path_override` to fix `test_rules_scala_win`.

Escaping `}` and `{` characters in the previous commit allowed the
`test_bzlmod_macros` tests to run on Linux and Windows. Then
`test_rules_scala_jdk21` failed with:

```txt
[FATAL 17:39:54.401 src/main/cpp/blaze.cc:1105]
  Unexpected error reading config file
  '/workdir/tmp/test_bzlmod_macros/tools/bazel.rc':
  (error: 2): No such file or directory"

Test "test_bzlmod_single_tag_values_returns_defaults_when_no_root_tag"
  failed  (0 sec)
```

`test_rules_scala_win` failed with a malformed looking error message:

```txt
ERROR: <builtin>: fetching local_repository rule //:rules_scala+:
  java.io.IOException: Could not create symlink to repository
  "/c/b/bk-windows-j20f/bazel/rules-scala-scala"
  (absolute path: "/c/b/bk-windows-j20f/bazel/rules-scala-scala"):
  Cannot create junction
  (name=C:	ools\msys64\hom\_bazel_b ules_scala+, target=

Test "test_bzlmod_single_tag_values_returns_defaults_when_no_root_tag"
  failed (3 sec)
```

Recreating this in a local Windows VM revealed a problem with
`_print_error_message()` that also mangled local error messages:

```txt
Value did not match regular expression
Expected: "foo bar baz$"
test/shell/test_helper.sh: line 148:
  printf: missing unicode digit for \u

Actual:   "Computing main repo mapping:
ERROR: <builtin>: fetching local_repository rule //:rules_scala+:
java.io.IOException: Could not create symlink to repository
"/c/Users/msb/src/bazelbuild/rules_ules_scala+, target=h:
"/c/Users/msb/src/bazelbuild/rules_scala"): Cannot create junction
(name=C:\users\msb\_bazel_msb\ieysfhucternal

Test "test_bzlmod_single_tag_values_returns_defaults_when_no_root_tag"
  failed  (0 sec)
```

Fixing it (changing the `%b` specifier for `printf` to `%s`) revealed a
more comprehensible error:

```txt
Value did not match regular expression
Expected: "foo bar baz$"
Actual:   "Computing main repo mapping:
ERROR: <builtin>: fetching local_repository rule //:rules_scala+:
  java.io.IOException: Could not create symlink to repository
  "/c/Users/msb/src/bazelbuild/rules_scala"
  (absolute path: "/c/Users/msb/src/bazelbuild/rules_scala"):
  Cannot create junction
  (name=C:\users\msb\_bazel_msb\ieysfhuc\external\rules_scala+,
   target=\c\Users\msb\src\bazelbuild\rules_scala):
ERROR: src/main/native/windows/file-jni.cc(122):
  nativeCreateJunction(
    \\?\C:\users\msb\_bazel_msb\ieysfhuc\external\rules_scala+,
    \\?\\c\Users\msb\src\bazelbuild\rules_scala):
ERROR: src/main/native/windows/file.cc(231):
  CreateJunction(\\?\\c\Users\msb\src\bazelbuild\rules_scala):
  expected an absolute Windows path for junction_target

ERROR: Error computing the main repository mapping:
  error during computation of main repo mapping:
  Could not create symlink to repository
  "/c/Users/msb/src/bazelbuild/rules_scala"
  (absolute path: "/c/Users/msb/src/bazelbuild/rules_scala"):
  Cannot create junction
  (name=C:\users\msb\_bazel_msb\ieysfhuc\external\rules_scala+,
   target=\c\Users\msb\src\bazelbuild\rules_scala):
ERROR: src/main/native/windows/file-jni.cc(122):
  nativeCreateJunction(
    \\?\C:\users\msb\_bazel_msb\ieysfhuc\external\rules_scala+,
    \\?\\c\Users\msb\src\bazelbuild\rules_scala):
ERROR: src/main/native/windows/file.cc(231):
  CreateJunction(\\?\\c\Users\msb\src\bazelbuild\rules_scala):
  expected an absolute Windows path for junction_target"

Test "test_bzlmod_single_tag_values_returns_defaults_when_no_root_tag"
  failed  (0 sec)
```

This shows clearly that the MSYS2 mapping of `C:\` paths to `/c/` breaks
the underlying symlink operation:

- https://github.com/bazelbuild/bazel/blob/release-7.6.0/src/main/java/com/google/devtools/build/lib/rules/repository/RepositoryDelegatorFunction.java#L508-L517

The fix was to use relative paths instead of absolute paths in the
`local_path_override` directives of the generated `MODULE.bazel` files.