Fix last_green build after disable_autoloads flip
Explicitly loads all symbols affected by
`--incompatible_disable_autoloads_in_main_repo` to fix `last_green`
Bazel builds. Adds `rules_shell` as a dev dependency and updates files
to fix `test_bzlmod_macros.sh` and `test_dependency_versions.sh`.

As a result of using Buildifier to add the missing `load` statements,
Buildifier reordered the `load` statements as well.

Fixes the following breakage when using the `last_green` build from
bazelbuild/bazel@f08d561385a5bcbd2f7e5341820fe35cc813bdd3 (and other
breakages blocked by this one):

```sh
$ bazel run //tools:lint_check

ERROR: scala/private/rules/scala_test.bzl:130:21:
  name 'JavaInfo' is not defined

ERROR: .../external/+dev_deps+com_github_bazelbuild_buildtools/buildifier/BUILD.bazel:3:10:
  While resolving toolchains for target
  @@+dev_deps+com_github_bazelbuild_buildtools//buildifier:buildifier
  (b5bbebe): invalid registered toolchain
  '//test/proto:scalapb_toolchain':
  error loading package 'test/proto':
  at /Users/mbland/src/bazel-contrib/rules_scala/scala/scala.bzl:35:5:
  compilation of module 'scala/private/rules/scala_test.bzl' failed

ERROR: Analysis of target '//tools:lint_check' failed; build aborted:
  Analysis failed
```

Fixed using Buildifier 8.2.0 by first running the following to get the
list of appropriate warnings:

```txt
buildifier --lint=warn -r . 2>&1 | grep -- native- |
  awk '{print $2}' | sort | uniq
```

then running:

```txt
buildifier --lint=fix \
  --warnings=native-java-common,native-java-info,native-sh-test,native-sh-binary \
  -r .
```

I also ran it separately on the changed files in `deps/test` and
`scala/private/macros/test`, since Buildifier didn't automatically find
them.

---

bazelbuild/bazel@d87eaf5d6fd41b54da59708f859fd80da8fcd303 from
2025-05-08 at 8:03am EDT flipped
`--incompatible_disable_autoloads_in_main_repo` to `true` to prepare for
Bazel 9. I did confirm that setting
`--noincompatible_disable_autoloads_in_main_repo` resolved the breakage
before using Buildifier to add the necessary `load` statements.

Pull request #1735 was the last to pass the `last_green` CI build using
bazelbuild/bazel@94e0b442cc44859f62a8081d8ffba7051ab6199e from
2025-05-08 at 7:39am EDT. This was two commits before the commit that
flipped `--incompatible_disable_autoloads_in_main_repo`:

- https://buildkite.com/bazel/rules-scala-scala/builds/5596#0196afc2-4af3-4202-8232-d5f5fe113349

Pull request #1736 failed the `last_green` CI build using
bazelbuild/bazel@cac54c46e5fd14b202066e7da8d05ddc098357c5 from
2025-05-09 at 6:14am EDT. That job ran on 2025-05-09 at 6:47am EDT. The
`last_green` configuration in `.bazelci/presubmit.yml` emits a warning
if the build fails. This warning was present on the build page, but
we've overlooked it until now:

- https://buildkite.com/bazel/rules-scala-scala/builds/5598#0196b4a8-e593-431a-ab4c-8d8471d9b08b

Part of this change copies more files from `test/jmh` into the
`test_dependency_versions.sh` test directory. It also replicates targets
from `//test/jmh` in `deps/test/BUILD.bazel.test` to replace
the previous dependency on `@rules_scala//test/jmh:add_numbers`.

This is because `//test/jmh` now has a `load` dependency on
`@rules_shell`, which is a `dev_dependency` of `@rules_scala`. Since
`@rules_shell` isn't visible to `@rules_scala` when it isn't the root
module, this broke the build within `test_dependency_versions.sh`.