Bump ScalaPB and gRPC, exclude listenablefuture
Adds these versions to `scripts/create_repository.py`.

There are breakages still that future commits will address, but the
following are fixed in this one.

Removes the unnecessary `true` parameter from `.getPlaintext(true)` in
`test/TestServer.scala` to fix this error after the gRPC bump:

```txt
ERROR: .../test/BUILD:676:14:
  scala @//test:lib_with_scala_proto_dep failed:
  (Exit 1): scalac failed: error executing command
  (from target //test:lib_with_scala_proto_dep)
  bazel-bin/src/java/io/bazel/rulesscala/scalac/scalac
    @bazel-out/darwin_arm64-fastbuild/bin/test/lib_with_scala_proto_dep.jar-0.params

test/TestServer.scala:70: error: no arguments allowed for nullary method usePlaintext: ()?0
    val channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext(true).build
                                                                            ^
```

We exclude `com.google.guava:listenablefuture` because trying to
download it breaks the build with an HTTP 404 (everything builds fine
without it anyway):

```txt
INFO: repository @io_bazel_rules_scala_listenablefuture' used the
  following cache hits instead of downloading the corresponding file.
  * Hash '...' for https://repo.maven.apache.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar

WARNING: Download from
  https://repo.maven.apache.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar
  failed: class java.io.FileNotFoundException GET returned 404 Not Found

WARNING: Download from
  https://maven-central.storage-download.googleapis.com/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar
  failed: class java.io.FileNotFoundException GET returned 404 Not Found

WARNING: Download from
  https://mirror.bazel.build/repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar
  failed: class java.io.FileNotFoundException GET returned 404 Not Found

WARNING: Download from
https://jcenter.bintray.com/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-sources.jar
  failed: class java.io.FileNotFoundException GET returned 404 Not Found

ERROR: An error occurred during the fetch of repository 'io_bazel_rules_scala_listenablefuture':
  Traceback (most recent call last):
    File ".../scala/scala_maven_import_external.bzl",
    line 130, column 32, in _jvm_import_external
      repository_ctx.download(srcurls, srcpath, srcsha, auth = _get_auth(repository_ctx, srcurls))

Error in download: java.io.IOException: Error downloading
  [ ...4 URLs from WARNINGs above... ]
to .../external/io_bazel_rules_scala_listenablefuture/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava-src.jar:
GET returned 404 Not Found

ERROR: /Users/mbland/src/bazelbuild/rules_scala/WORKSPACE:75:25:
  fetching jvm_import_external rule
  //external:io_bazel_rules_scala_listenablefuture:
  [ ...Traceback, java.io.IOException, and HTTP 404 from above... ]

ERROR: .../external/io_bazel_rules_scala_guava/BUILD:9:13:
  @io_bazel_rules_scala_guava//:io_bazel_rules_scala_guava depends on
  @io_bazel_rules_scala_listenablefuture//:io_bazel_rules_scala_listenablefuture
  in repository @io_bazel_rules_scala_listenablefuture
  which failed to fetch. no such package
  '@io_bazel_rules_scala_listenablefuture//':
     [ ...java.io.IOException and HTTP 404 from above... ]

ERROR: Analysis of target
  '//test/proto/custom_generator:failing_scala_proto_deps_toolchain_def'
  failed; build aborted:
```