Fix all test_examples and test_version WORKSPACEs
Updated the `WORKSPACE` to import fewer protobuf deps, which required
importing an up to date `@platforms` and `@rules_pkg` earlier in the
file. Copied these setup stanzas to all the testing example projects
that need it.

`./test_examples.sh` now passes completely. `bazel build //test/...` and
`./test_version.sh` still hang, but the latter doesn't break on its
`WORKSPACE` configuration.

---

My working theory is that this breakage from `bazel build
//test/proto3:all` provides a hint as to why the other protoc jobs hang:

```txt
ERROR: .../test/proto3/BUILD:14:14: ProtoScalaPBRule
  test/proto3/generated-proto-lib_jvm_extra_protobuf_generator_scalapb.srcjar
  failed: (Exit 1): scalapb_worker failed:
  error executing ProtoScalaPBRule command
  (from target //test/proto3:generated-proto-lib)

bazel-out/darwin_arm64-opt-exec-ST-a828a81199fe/bin/src/scala/scripts/scalapb_worker
... (remaining 2 arguments skipped)

Could not find file in descriptor database:
  bazel-out/darwin_arm64-fastbuild/bin/test/proto3/generated.proto:
  No such file or directory

java.lang.RuntimeException: Exit with code 1
        at scala.sys.package$.error(package.scala:30)
        at scripts.ScalaPBWorker$.work(ScalaPBWorker.scala:44)
        at io.bazel.rulesscala.worker.Worker.persistentWorkerMain(Worker.java:96)
        at io.bazel.rulesscala.worker.Worker.workerMain(Worker.java:49)
        at scripts.ScalaPBWorker$.main(ScalaPBWorker.scala:39)
        at scripts.ScalaPBWorker.main(ScalaPBWorker.scala)
Use --verbose_failures to see the command lines of failed build steps.

ERROR: .../test/proto3/BUILD:14:14 Building source jar
bazel-out/darwin_arm64-fastbuild/bin/test/proto3/generated-proto-lib_scalapb-src.jar
failed: (Exit 1): scalapb_worker failed: error executing
ProtoScalaPBRule command (from target //test/proto3:generated-proto-lib)

bazel-out/darwin_arm64-opt-exec-ST-a828a81199fe/bin/src/scala/scripts/scalapb_worker
... (remaining 2 arguments skipped)
```

If we can fix this, I think we might fix the hanging jobs, too.

---

I'm focusing on this problem because migrating to Bzlmod will require
using these newer versions of `@rules_proto` and `@com_google_protobuf`.
It's the same problem I saw after successfully building the rest of the
repo under Bzlmod, and it keeps these dependencies revlocked even under
`WORKSPACE`. It's a problem that we need to solve one way or the other.

I also tried to revert everything else to master but `@rules_proto` and
`@com_google_protobuf`, but that didn't work. I wound up having to creep
up the versions of other packages until I'd updated most of them again.
I can try to update Bazel and all the dependencies _other_ than
`@rules_proto` and `@com_google_protobuf` and get those merged first, if
that's possible. Then I can try to create a pull request focused only on
the protobuf problem.

---

On another note:

Now I know why `WORKSPACE` must be destroyed. I tried creating macros
for these protobuf dependency stanzas, but was stymied by repo ordering
errors. Duplicating all these stanzas has made me feel rather filthy.

Bzlmod is definitely a superior experience once it's implemented. All of
this config will just live in the top level rules_scala module. These
example projects won't have to duplicate anything but the
statements required to import it.