Add org_scala_lang_modules_scala_collection_compat
More specifically, add it to the list of core scala repository imports.
It had been generated before, but somehow hadn't been required until
now.

With this change, all tests now pass after the ScalaPB 0.11.17, gRPC
1.68.1, and Guava 33.3.1-jre version bumps.

Fixes the following error in `test_scala_version 2.12.20` from
`test_version.sh`:

```txt
ERROR: .../external/scala_proto_rules_scalapb_compilerplugin/BUILD:9:13:
  no such package '@org_scala_lang_modules_scala_collection_compat//':

  The repository '@org_scala_lang_modules_scala_collection_compat'
  could not be resolved:

  Repository '@org_scala_lang_modules_scala_collection_compat'
  is not defined and referenced by
  '@scala_proto_rules_scalapb_compilerplugin//:scala_proto_rules_scalapb_compilerplugin'

ERROR: Analysis of target '//proto:test_proto_nogrpc' failed; build aborted:
```